language: php

sudo: false

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly


script: 
  - php -d error_reporting=E_ALL -d error_log=error.log -d log_errors=1 example/example.php
  - if [ -f "error.log" ]; then cat error.log; `exit 1;`; fi
