language: php
sudo: false
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.2


script: 
  - php -d error_reporting=E_ALL -d error_log=error.log -d log_errors=1 example/example.php
  - if [ -f "error.log" ]; then cat error.log; `exit 1;`; fi
